server {
    listen 80;
    server_name web-app-backend.duckdns.org;
    
    # Redirect all HTTP traffic to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name web-app-backend.duckdns.org;

    # SSL Certificate Paths
    ssl_certificate /etc/letsencrypt/live/web-app-backend.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/web-app-backend.duckdns.org/privkey.pem;

    # Performance and Security Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

   location /api/ {
    proxy_pass http://backend-api:5000;

    # Just pass the real user info to Express
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}

    # Root location (Optional: for serving a frontend or a fallback)
    location / {
        proxy_pass http://backend-api:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}